"""base schema

Revision ID: 85a90f92461b
Revises:
Create Date: 2026-07-30 00:48:52.850330
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = "85a90f92461b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("subject", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_users")),
        sa.UniqueConstraint("subject", name=op.f("uq_admin_users_subject")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("actor_type", sa.String(length=24), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=26), nullable=False),
        sa.Column("before_json", sa.JSON(), nullable=True),
        sa.Column("after_json", sa.JSON(), nullable=True),
        sa.Column("request_id", sa.String(length=26), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_table(
        "client_apps",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("key_id", sa.String(length=64), nullable=False),
        sa.Column("secret_digest", sa.String(length=64), nullable=False),
        sa.Column("allowed_package_ids_json", sa.JSON(), nullable=True),
        sa.Column("allowed_media_hosts_json", sa.JSON(), nullable=True),
        sa.Column("rate_limit_per_minute", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client_apps")),
        sa.UniqueConstraint("code", name=op.f("uq_client_apps_code")),
        sa.UniqueConstraint("key_id", name=op.f("uq_client_apps_key_id")),
    )
    op.create_table(
        "curriculum_packages",
        sa.Column("code", sa.String(length=96), nullable=False),
        sa.Column("subject_code", sa.String(length=32), nullable=False),
        sa.Column("grade", sa.SmallInteger(), nullable=False),
        sa.Column("semester", sa.String(length=16), nullable=False),
        sa.Column("edition", sa.String(length=128), nullable=False),
        sa.Column("publisher", sa.String(length=128), nullable=True),
        sa.Column("curriculum_standard", sa.String(length=128), nullable=True),
        sa.Column("region_json", sa.JSON(), nullable=True),
        sa.Column("current_release_id", sa.String(length=26), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_curriculum_packages")),
        sa.UniqueConstraint("code", name=op.f("uq_curriculum_packages_code")),
    )
    op.create_index(
        "ix_packages_subject_grade_semester_status",
        "curriculum_packages",
        ["subject_code", "grade", "semester", "status"],
        unique=False,
    )
    op.create_table(
        "admin_user_roles",
        sa.Column("admin_user_id", sa.String(length=26), nullable=False),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("package_id", sa.String(length=26), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_admin_user_roles_admin_user_id_admin_users"),
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["curriculum_packages.id"],
            name=op.f("fk_admin_user_roles_package_id_curriculum_packages"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_user_roles")),
        sa.UniqueConstraint(
            "admin_user_id",
            "role",
            "package_id",
            name=op.f("uq_admin_user_roles_admin_user_id"),
        ),
    )
    op.create_table(
        "package_versions",
        sa.Column("package_id", sa.String(length=26), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("based_on_version_id", sa.String(length=26), nullable=True),
        sa.Column("release_notes", sa.Text(), nullable=True),
        sa.Column("benchmark_result_json", sa.JSON(), nullable=True),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("reviewed_by", sa.String(length=128), nullable=True),
        sa.Column("published_by", sa.String(length=128), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["based_on_version_id"],
            ["package_versions.id"],
            name=op.f("fk_package_versions_based_on_version_id_package_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["curriculum_packages.id"],
            name=op.f("fk_package_versions_package_id_curriculum_packages"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_package_versions")),
        sa.UniqueConstraint(
            "package_id", "version", name=op.f("uq_package_versions_package_id")
        ),
    )
    op.create_index(
        op.f("ix_package_versions_package_id"),
        "package_versions",
        ["package_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_package_versions_package_id"), table_name="package_versions")
    op.drop_table("package_versions")
    op.drop_table("admin_user_roles")
    op.drop_index(
        "ix_packages_subject_grade_semester_status", table_name="curriculum_packages"
    )
    op.drop_table("curriculum_packages")
    op.drop_table("client_apps")
    op.drop_table("audit_logs")
    op.drop_table("admin_users")
    # ### end Alembic commands ###
