"""catalog schema

Revision ID: 8ae2498b1729
Revises: 85a90f92461b
Create Date: 2026-07-30 00:48:55.267400
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = "8ae2498b1729"
down_revision: Union[str, Sequence[str], None] = "85a90f92461b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gold_test_cases",
        sa.Column("package_id", sa.String(length=26), nullable=False),
        sa.Column("question_json", sa.JSON(), nullable=False),
        sa.Column("scope_context_json", sa.JSON(), nullable=True),
        sa.Column("expected_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["curriculum_packages.id"],
            name=op.f("fk_gold_test_cases_package_id_curriculum_packages"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gold_test_cases")),
    )
    op.create_table(
        "curriculum_nodes",
        sa.Column("logical_id", sa.String(length=26), nullable=False),
        sa.Column("package_version_id", sa.String(length=26), nullable=False),
        sa.Column("parent_id", sa.String(length=26), nullable=True),
        sa.Column("node_type", sa.String(length=24), nullable=False),
        sa.Column("code", sa.String(length=96), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("order_no", sa.Integer(), nullable=False),
        sa.Column("source_json", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["package_version_id"],
            ["package_versions.id"],
            name=op.f("fk_curriculum_nodes_package_version_id_package_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["curriculum_nodes.id"],
            name=op.f("fk_curriculum_nodes_parent_id_curriculum_nodes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_curriculum_nodes")),
        sa.UniqueConstraint(
            "package_version_id", "logical_id", name="uq_nodes_version_logical"
        ),
        sa.UniqueConstraint(
            "package_version_id",
            "parent_id",
            "order_no",
            name="uq_nodes_version_parent_order",
        ),
    )
    op.create_index(
        op.f("ix_curriculum_nodes_package_version_id"),
        "curriculum_nodes",
        ["package_version_id"],
        unique=False,
    )
    op.create_table(
        "exemplars",
        sa.Column("logical_id", sa.String(length=26), nullable=False),
        sa.Column("package_version_id", sa.String(length=26), nullable=False),
        sa.Column("exemplar_type", sa.String(length=24), nullable=False),
        sa.Column("source_type", sa.String(length=24), nullable=False),
        sa.Column("source_json", sa.JSON(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("options_json", sa.JSON(), nullable=True),
        sa.Column("answer_json", sa.JSON(), nullable=True),
        sa.Column("solution_text", sa.Text(), nullable=True),
        sa.Column("task_signature_json", sa.JSON(), nullable=False),
        sa.Column("media_json", sa.JSON(), nullable=True),
        sa.Column("display_level", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["package_version_id"],
            ["package_versions.id"],
            name=op.f("fk_exemplars_package_version_id_package_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exemplars")),
        sa.UniqueConstraint(
            "package_version_id",
            "logical_id",
            name=op.f("uq_exemplars_package_version_id"),
        ),
    )
    op.create_index(
        op.f("ix_exemplars_package_version_id"),
        "exemplars",
        ["package_version_id"],
        unique=False,
    )
    op.create_index(
        "ix_exemplars_version_type_status",
        "exemplars",
        ["package_version_id", "exemplar_type", "status"],
        unique=False,
    )
    op.create_table(
        "import_jobs",
        sa.Column("package_version_id", sa.String(length=26), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("preview_json", sa.JSON(), nullable=True),
        sa.Column("errors_json", sa.JSON(), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=True),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["package_version_id"],
            ["package_versions.id"],
            name=op.f("fk_import_jobs_package_version_id_package_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_jobs")),
        sa.UniqueConstraint(
            "package_version_id",
            "source_hash",
            name=op.f("uq_import_jobs_package_version_id"),
        ),
    )
    op.create_table(
        "regression_runs",
        sa.Column("package_version_id", sa.String(length=26), nullable=False),
        sa.Column("classifier_version", sa.String(length=64), nullable=False),
        sa.Column("metrics_json", sa.JSON(), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["package_version_id"],
            ["package_versions.id"],
            name=op.f("fk_regression_runs_package_version_id_package_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regression_runs")),
    )
    op.create_table(
        "objectives",
        sa.Column("logical_id", sa.String(length=26), nullable=False),
        sa.Column("package_version_id", sa.String(length=26), nullable=False),
        sa.Column("node_id", sa.String(length=26), nullable=False),
        sa.Column("code", sa.String(length=96), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("attainment", sa.Text(), nullable=False),
        sa.Column("required_concepts_json", sa.JSON(), nullable=False),
        sa.Column("required_actions_json", sa.JSON(), nullable=False),
        sa.Column("allowed_variations_json", sa.JSON(), nullable=False),
        sa.Column("exclusions_json", sa.JSON(), nullable=False),
        sa.Column("match_hints_json", sa.JSON(), nullable=True),
        sa.Column("source_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["curriculum_nodes.id"],
            name=op.f("fk_objectives_node_id_curriculum_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["package_version_id"],
            ["package_versions.id"],
            name=op.f("fk_objectives_package_version_id_package_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_objectives")),
        sa.UniqueConstraint(
            "package_version_id", "code", name="uq_objectives_version_code"
        ),
        sa.UniqueConstraint(
            "package_version_id", "logical_id", name="uq_objectives_version_logical"
        ),
    )
    op.create_index(
        op.f("ix_objectives_package_version_id"),
        "objectives",
        ["package_version_id"],
        unique=False,
    )
    op.create_index(
        "ix_objectives_version_node_status",
        "objectives",
        ["package_version_id", "node_id", "status"],
        unique=False,
    )
    op.create_table(
        "exemplar_objectives",
        sa.Column("exemplar_id", sa.String(length=26), nullable=False),
        sa.Column("objective_id", sa.String(length=26), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["exemplar_id"],
            ["exemplars.id"],
            name=op.f("fk_exemplar_objectives_exemplar_id_exemplars"),
        ),
        sa.ForeignKeyConstraint(
            ["objective_id"],
            ["objectives.id"],
            name=op.f("fk_exemplar_objectives_objective_id_objectives"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exemplar_objectives")),
        sa.UniqueConstraint(
            "exemplar_id",
            "objective_id",
            "role",
            name=op.f("uq_exemplar_objectives_exemplar_id"),
        ),
    )
    op.create_index(
        op.f("ix_exemplar_objectives_exemplar_id"),
        "exemplar_objectives",
        ["exemplar_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exemplar_objectives_objective_id"),
        "exemplar_objectives",
        ["objective_id"],
        unique=False,
    )
    op.create_table(
        "objective_external_mappings",
        sa.Column("package_version_id", sa.String(length=26), nullable=False),
        sa.Column("objective_id", sa.String(length=26), nullable=False),
        sa.Column("namespace", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["objective_id"],
            ["objectives.id"],
            name=op.f("fk_objective_external_mappings_objective_id_objectives"),
        ),
        sa.ForeignKeyConstraint(
            ["package_version_id"],
            ["package_versions.id"],
            name=op.f(
                "fk_objective_external_mappings_package_version_id_package_versions"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_objective_external_mappings")),
        sa.UniqueConstraint(
            "package_version_id",
            "namespace",
            "external_id",
            name=op.f("uq_objective_external_mappings_package_version_id"),
        ),
    )
    op.create_index(
        op.f("ix_objective_external_mappings_objective_id"),
        "objective_external_mappings",
        ["objective_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_objective_external_mappings_package_version_id"),
        "objective_external_mappings",
        ["package_version_id"],
        unique=False,
    )
    op.create_table(
        "objective_relations",
        sa.Column("package_version_id", sa.String(length=26), nullable=False),
        sa.Column("source_objective_id", sa.String(length=26), nullable=False),
        sa.Column("target_objective_id", sa.String(length=26), nullable=False),
        sa.Column("relation_type", sa.String(length=24), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["package_version_id"],
            ["package_versions.id"],
            name=op.f("fk_objective_relations_package_version_id_package_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["source_objective_id"],
            ["objectives.id"],
            name=op.f("fk_objective_relations_source_objective_id_objectives"),
        ),
        sa.ForeignKeyConstraint(
            ["target_objective_id"],
            ["objectives.id"],
            name=op.f("fk_objective_relations_target_objective_id_objectives"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_objective_relations")),
        sa.UniqueConstraint(
            "package_version_id",
            "source_objective_id",
            "target_objective_id",
            "relation_type",
            name=op.f("uq_objective_relations_package_version_id"),
        ),
    )
    op.create_index(
        op.f("ix_objective_relations_package_version_id"),
        "objective_relations",
        ["package_version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_objective_relations_package_version_id"),
        table_name="objective_relations",
    )
    op.drop_table("objective_relations")
    op.drop_index(
        op.f("ix_objective_external_mappings_package_version_id"),
        table_name="objective_external_mappings",
    )
    op.drop_index(
        op.f("ix_objective_external_mappings_objective_id"),
        table_name="objective_external_mappings",
    )
    op.drop_table("objective_external_mappings")
    op.drop_index(
        op.f("ix_exemplar_objectives_objective_id"), table_name="exemplar_objectives"
    )
    op.drop_index(
        op.f("ix_exemplar_objectives_exemplar_id"), table_name="exemplar_objectives"
    )
    op.drop_table("exemplar_objectives")
    op.drop_index("ix_objectives_version_node_status", table_name="objectives")
    op.drop_index(op.f("ix_objectives_package_version_id"), table_name="objectives")
    op.drop_table("objectives")
    op.drop_table("regression_runs")
    op.drop_table("import_jobs")
    op.drop_index("ix_exemplars_version_type_status", table_name="exemplars")
    op.drop_index(op.f("ix_exemplars_package_version_id"), table_name="exemplars")
    op.drop_table("exemplars")
    op.drop_index(
        op.f("ix_curriculum_nodes_package_version_id"), table_name="curriculum_nodes"
    )
    op.drop_table("curriculum_nodes")
    op.drop_table("gold_test_cases")
    # ### end Alembic commands ###
