"""classification schema

Revision ID: b387cfd200d0
Revises: 8ae2498b1729
Create Date: 2026-07-30 00:48:57.767536
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = "b387cfd200d0"
down_revision: Union[str, Sequence[str], None] = "8ae2498b1729"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classification_tasks",
        sa.Column("client_app_id", sa.String(length=26), nullable=False),
        sa.Column("client_request_id", sa.String(length=128), nullable=False),
        sa.Column("source_question_id", sa.String(length=128), nullable=True),
        sa.Column("active_package_version_id", sa.String(length=26), nullable=False),
        sa.Column("request_json", sa.JSON(), nullable=False),
        sa.Column("question_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("processing_started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("failure_code", sa.String(length=64), nullable=True),
        sa.Column("failure_message", sa.String(length=512), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["active_package_version_id"],
            ["package_versions.id"],
            name=op.f(
                "fk_classification_tasks_active_package_version_id_package_versions"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["client_app_id"],
            ["client_apps.id"],
            name=op.f("fk_classification_tasks_client_app_id_client_apps"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classification_tasks")),
        sa.UniqueConstraint(
            "client_app_id",
            "client_request_id",
            name=op.f("uq_classification_tasks_client_app_id"),
        ),
    )
    op.create_index(
        op.f("ix_classification_tasks_client_app_id"),
        "classification_tasks",
        ["client_app_id"],
        unique=False,
    )
    op.create_index(
        "ix_tasks_hash_version",
        "classification_tasks",
        ["question_hash", "active_package_version_id"],
        unique=False,
    )
    op.create_index(
        "ix_tasks_status_created",
        "classification_tasks",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "classification_feedback",
        sa.Column("classification_id", sa.String(length=26), nullable=False),
        sa.Column("client_app_id", sa.String(length=26), nullable=False),
        sa.Column("feedback_request_id", sa.String(length=128), nullable=False),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column("correction_json", sa.JSON(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["classification_id"],
            ["classification_tasks.id"],
            name=op.f(
                "fk_classification_feedback_classification_id_classification_tasks"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["client_app_id"],
            ["client_apps.id"],
            name=op.f("fk_classification_feedback_client_app_id_client_apps"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classification_feedback")),
        sa.UniqueConstraint(
            "client_app_id",
            "feedback_request_id",
            name=op.f("uq_classification_feedback_client_app_id"),
        ),
    )
    op.create_index(
        op.f("ix_classification_feedback_classification_id"),
        "classification_feedback",
        ["classification_id"],
        unique=False,
    )
    op.create_table(
        "classification_task_packages",
        sa.Column("task_id", sa.String(length=26), nullable=False),
        sa.Column("package_version_id", sa.String(length=26), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["package_version_id"],
            ["package_versions.id"],
            name=op.f(
                "fk_classification_task_packages_package_version_id_package_versions"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["classification_tasks.id"],
            name=op.f("fk_classification_task_packages_task_id_classification_tasks"),
        ),
        sa.PrimaryKeyConstraint(
            "task_id",
            "package_version_id",
            name=op.f("pk_classification_task_packages"),
        ),
    )
    op.create_table(
        "classification_candidates",
        sa.Column("task_id", sa.String(length=26), nullable=False),
        sa.Column("objective_id", sa.String(length=26), nullable=False),
        sa.Column("rank_no", sa.Integer(), nullable=False),
        sa.Column("retrieval_score", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("feature_score_json", sa.JSON(), nullable=False),
        sa.Column("matched_exemplar_ids_json", sa.JSON(), nullable=False),
        sa.Column("conflicts_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["objective_id"],
            ["objectives.id"],
            name=op.f("fk_classification_candidates_objective_id_objectives"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["classification_tasks.id"],
            name=op.f("fk_classification_candidates_task_id_classification_tasks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classification_candidates")),
        sa.UniqueConstraint(
            "task_id", "objective_id", name="uq_candidates_task_objective"
        ),
        sa.UniqueConstraint("task_id", "rank_no", name="uq_candidates_task_rank"),
    )
    op.create_table(
        "classification_results",
        sa.Column("task_id", sa.String(length=26), nullable=False),
        sa.Column("primary_objective_id", sa.String(length=26), nullable=True),
        sa.Column("match_type", sa.String(length=16), nullable=False),
        sa.Column("scope_status", sa.String(length=20), nullable=False),
        sa.Column("confidence_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("requires_confirmation", sa.Boolean(), nullable=False),
        sa.Column("reason_summary", sa.String(length=1000), nullable=False),
        sa.Column("task_signature_json", sa.JSON(), nullable=True),
        sa.Column("classifier_version", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["primary_objective_id"],
            ["objectives.id"],
            name=op.f("fk_classification_results_primary_objective_id_objectives"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["classification_tasks.id"],
            name=op.f("fk_classification_results_task_id_classification_tasks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classification_results")),
        sa.UniqueConstraint("task_id", name=op.f("uq_classification_results_task_id")),
    )
    op.create_table(
        "feedback_reviews",
        sa.Column("feedback_id", sa.String(length=26), nullable=False),
        sa.Column("reviewer_subject", sa.String(length=128), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("action_type", sa.String(length=24), nullable=False),
        sa.Column("review_note", sa.Text(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["feedback_id"],
            ["classification_feedback.id"],
            name=op.f("fk_feedback_reviews_feedback_id_classification_feedback"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback_reviews")),
        sa.UniqueConstraint(
            "feedback_id", name=op.f("uq_feedback_reviews_feedback_id")
        ),
    )
    op.create_table(
        "classification_evidence",
        sa.Column("result_id", sa.String(length=26), nullable=False),
        sa.Column("exemplar_id", sa.String(length=26), nullable=False),
        sa.Column("objective_id", sa.String(length=26), nullable=False),
        sa.Column("reason_summary", sa.String(length=500), nullable=False),
        sa.Column("display_level", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["exemplar_id"],
            ["exemplars.id"],
            name=op.f("fk_classification_evidence_exemplar_id_exemplars"),
        ),
        sa.ForeignKeyConstraint(
            ["objective_id"],
            ["objectives.id"],
            name=op.f("fk_classification_evidence_objective_id_objectives"),
        ),
        sa.ForeignKeyConstraint(
            ["result_id"],
            ["classification_results.id"],
            name=op.f("fk_classification_evidence_result_id_classification_results"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classification_evidence")),
    )
    op.create_table(
        "classification_result_objectives",
        sa.Column("result_id", sa.String(length=26), nullable=False),
        sa.Column("objective_id", sa.String(length=26), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("rank_no", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["objective_id"],
            ["objectives.id"],
            name=op.f("fk_classification_result_objectives_objective_id_objectives"),
        ),
        sa.ForeignKeyConstraint(
            ["result_id"],
            ["classification_results.id"],
            name=op.f(
                "fk_classification_result_objectives_result_id_classification_results"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "result_id",
            "objective_id",
            name=op.f("pk_classification_result_objectives"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("classification_result_objectives")
    op.drop_table("classification_evidence")
    op.drop_table("feedback_reviews")
    op.drop_table("classification_results")
    op.drop_table("classification_candidates")
    op.drop_table("classification_task_packages")
    op.drop_index(
        op.f("ix_classification_feedback_classification_id"),
        table_name="classification_feedback",
    )
    op.drop_table("classification_feedback")
    op.drop_index("ix_tasks_status_created", table_name="classification_tasks")
    op.drop_index("ix_tasks_hash_version", table_name="classification_tasks")
    op.drop_index(
        op.f("ix_classification_tasks_client_app_id"), table_name="classification_tasks"
    )
    op.drop_table("classification_tasks")
    # ### end Alembic commands ###
